### ISSUE TITLE
Unable to output message after task message

### ISSUE THREAD

**Issue by vitormv** [privatenumber/tasuku#16]
## Bug description
I want to output a message AFTER all the tasks have run, but it seems Tasuku somehow always hijacks the order of messages. I tried to use `.then()` and await the task itself, but no success...

How can I ensure my message is displayed AFTER the task messages?

## Reproduction

```js
import task from 'tasuku';

const delay = (ms) => {
    return new Promise(function(resolve) {
        setTimeout(resolve, ms);
    });
}

const response = await
  task( `My task`, () => (delay(100)))
  .then(() => {
    console.log('THEN command');
  });

console.log('should print after response, no?');
```

## Output
<img width="651" alt="Screenshot 2022-04-08 at 11 59 06" src="https://user-images.githubusercontent.com/183328/162467655-efc23694-2119-40cc-862e-5e8bd33be0d4.png">

## Environment
- tasuku version: 1.0.2
- Operating System: OSX Monterey 12.2.1
- Node version: v14.18.2
- Package manager (npm/yarn/pnpm) and version:

**Comment by mixn** [comment]
@vitormv Did you manage to solve this somehow? I’m like 80% into migrating a big CLI from Listr to tasuku and am only now noticing that I’m having this issue. 😨 Really need to be able to give some final feedback once the last tasuku task has finished. 

Thanks in advance.

**Comment by privatenumber** [comment]
This is addressed in `tasuku@beta` with the inline renderer. Tasks render sequentially — console output appears exactly where you'd expect:

```ts
import task from 'tasuku/inline'

await task('My task', async () => {
    await delay(100)
})

console.log('This prints after the task')
```

Try it out: `npm i tasuku@beta`

Source: https://github.com/privatenumber/tasuku/tree/beta

**Comment by Tobbe** [comment]
I wanted to try this, but getting a bunch of red squiggles when I upgrade to the beta version.
And when I try to run it I get this error
```
TypeError: Cannot read properties of undefined (reading 'group')
    at /Users/tobbe/dev/cedarjs/cedar/packages/codemods/dist/codemods/v2.7.x/prismaV7Prep/prismaV7Prep.yargs.js:43:17
    at file:///Users/tobbe/dev/cedarjs/cedar/node_modules/tasuku/dist/patch-console-D3Ski1GW.mjs:3:2094
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_context_frame:63:14)
```

What are the breaking changes between v2.3.0 and 3.0.0-beta.4?

**Comment by privatenumber** [comment]
Hey @Tobbe! The error is from a breaking change in the beta — the `task` property was removed from the inner API. Nesting now works automatically via async context, so you just call `task()` directly:

```diff
- await task('Parent', async ({ task }) => {
-     await task.group(task => [ ... ])
+ await task('Parent', async () => {
+     await task.group(task => [ ... ])
  })
```

There are a few other breaking changes (return type, group results). Full migration guide here: https://github.com/privatenumber/tasuku/blob/beta/MIGRATION.md

Let me know if you run into anything else!
